apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:1.21.6 # Initial version of the image
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {} # Pause for manual verification
      - setWeight: 40
      - pause: {duration: 1m} # Pause for 1 minute
      - setWeight: 60
      - pause: {duration: 1m}
      - setWeight: 80
      - pause: {duration: 1m}
      - setWeight: 100
